baseURL = "https://example.org/"
languageCode = "en-us"
title = "My Hugo Site with Headless CMS"

# Hugo theme (we'll create a custom one)
theme = ""

# Enable build with remote resources
[build]
  writeStats = true
  noJSConfigInAssets = true

# Enable the GetRemote function for external API calls
[params]
  enableGetRemote = true

# Configure the site to work with headless CMS
[params.cms]
  endpoint = "https://api.your-cms.com/endpoint"
  # This will be replaced with your actual CMS endpoint

# Enable GraphQL support
[params.graphql]
  enabled = true

# Site metadata
[params.meta]
  description = "A Hugo site powered by headless CMS"
  keywords = ["hugo", "cms", "headless", "static-site"]
  author = "Your Name"
